export { default as Home } from './Home';
export { default as About } from './About';
export { default as Menu } from './Menu';
export { default as NoMatch } from './NoMatch';
export { default as Store } from './Store';
export { default as PurchasePage } from './PurchasePage';
export { default as Login } from './User/Login';
export { default as Register } from './User/Register';
export { default as Cart } from './Cart';
